using System.Text;
using System.Text.Json;

namespace BookmarkSync.Domain.Tests;

/// <summary>
/// The HLC vector <b>generator</b> plus guard tests around it.
/// </summary>
/// <remarks>
/// Generator and replayer deliberately live in different files: a past "generator
/// verifying itself" bug baked bad vectors into the file forever, undiscovered.
/// Split apart,
/// <see cref="HlcVectorTests"/> can verify an <b>independent</b> computation against <b>the same file</b>.
/// </remarks>
public class HlcVectorExportTests
{
    /// <summary>
    /// Walk HLC through a fixed script and produce the vectors file content.
    /// </summary>
    /// <returns>(JSON text, vector count)</returns>
    public static (string Blob, int Count) BuildVectors()
    {
        var clk = new FixedClock(1_700_000_000_000L);
        Hlc h = Hlc.NewWithClock(clk.Now);
        var vectors = new List<HlcVector>();

        // Only **one** method may be called here. The early Go form unconditionally called h.Now()
        // first and overwrote with h.Update() on op=="update" — so every update step secretly
        // ran an extra Now(), advancing state while discarding that Now() output.
        //
        // Consequence: vectors recorded a "one step too far" state no faithful replayer matches.
        // The JS side faithfully follows op, so it desyncs from the first update with a
        // "Go and C# disagree" symptom — pointing suspicion in a completely wrong direction.
        void Step(string op, string remote)
        {
            string output = op == "update" ? h.Update(remote) : h.Now();
            vectors.Add(new HlcVector { Op = op, Remote = remote, At = clk.Now(), Out = output });
        }

        // 1) Physical clock still, consecutive local events (told apart by logical counter)
        for (int i = 0; i < 5; i++)
        {
            Step("now", string.Empty);
        }

        // 2) Physical clock advances to a new millisecond (counter should reset)
        clk.Add(1500);
        Step("now", string.Empty);

        // 3) Remote counter higher within the same millisecond — the once-misimplemented causality branch
        Step("update", Hlc.Encode(clk.Now(), 40));
        Step("now", string.Empty);

        // 4) Remote millisecond larger
        Step("update", Hlc.Encode(clk.Now() + 60_000, 3));
        Step("now", string.Empty);

        // 5) Physical clock jumps far back
        clk.Add(-120_000);
        Step("now", string.Empty);

        // 6) Illegal remote timestamp (should degrade to pure local advance, no crash)
        Step("update", "not-an-hlc");
        Step("now", string.Empty);

        // 7) Remote counter overflow edge
        Step("update", Hlc.Encode(clk.Now(), 99_999));
        Step("now", string.Empty);

        // 8) Physical clock advances again, confirming post-overflow carry still works
        clk.Add(5);
        Step("now", string.Empty);
        Step("now", string.Empty);

        // 9) Remote timestamp exactly equals the current physical millisecond with counter 0
        Step("update", Hlc.Encode(clk.Now(), 0));
        Step("now", string.Empty);

        var file = new HlcVectorFileOut
        {
            Note = "Generated by the bmsync/tests/BookmarkSync.Domain.Tests vector generator. " +
                   "The JS side must reproduce every out exactly — divergent HLCs make merges nondeterministic.",
            Layout = Hlc.Layout,
            Vectors = vectors,
        };

        var options = new JsonSerializerOptions
        {
            WriteIndented = true,
            // Emit the note raw, matching the Go build
            Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        };

        string blob = JsonSerializer.Serialize(file, options) + "\n";
        return (blob, vectors.Count);
    }

    [Fact]
    public void GeneratorProducesEnoughVectors()
    {
        (string blob, int count) = BuildVectors();
        Assert.True(count >= 15, $"only produced {count} vectors, insufficient cross-client coverage");
        Assert.Contains("\"vectors\"", blob, StringComparison.Ordinal);
        Assert.Contains(Hlc.Layout, blob, StringComparison.Ordinal);
    }

    /// <summary>
    /// The generator output must round-trip through the replayer unchanged.
    /// </summary>
    /// <remarks>
    /// Covers "JSON shape disagrees with implementation convention" bugs: e.g. the generator writing
    /// PascalCase <c>Op/Remote/At/Out</c> while the replayer reads lowercase names,
    /// leaving every field at its zero value — and with no replayer assertions that yields 15
    /// "all passing" vacuous tests.
    /// </remarks>
    [Fact]
    public void GeneratorOutputRoundTripsThroughReplayer()
    {
        (string blob, _) = BuildVectors();
        var parsed = JsonSerializer.Deserialize(blob, TestJsonContext.Default.HlcVectorFile);

        Assert.NotNull(parsed);
        Assert.NotEmpty(parsed!.Vectors);
        Assert.All(parsed.Vectors, v =>
        {
            Assert.Contains(v.Op, new[] { "now", "update" });
            Assert.False(string.IsNullOrEmpty(v.Out));
            Assert.True(Hlc.IsValid(v.Out), $"vector output \"{v.Out}\" is not a valid HLC");
        });
    }

    /// <summary>
    /// When writing the vectors file, the target directory must already exist.
    /// </summary>
    /// <remarks>
    /// Lesson from a past incident: the legacy generator created missing
    /// directories automatically, so when the package moved and the path went stale
    /// the path went stale it created a fresh directory tree and "succeeded" — while Go and JS both
    /// kept reading the stale file at the repo root. <b>Green on both sides, yet cross-client
    /// verification never happened.</b>
    /// <para>
    /// This implementation deliberately creates no directories: a wrong path must be a hard error.
    /// </para>
    /// </remarks>
    [Fact]
    public void WriteVectors_RefusesWhenDirectoryMissing()
    {
        (string blob, int count) = BuildVectors();
        Assert.True(count > 0);

        string missingDir = Path.Combine(Path.GetTempPath(), "bmsync-no-such-" + Guid.NewGuid().ToString("N"), "test");
        string target = Path.Combine(missingDir, "hlc_vectors.json");

        // Only verify "we do not create a missing directory" here.
        // The real write path has a Directory.Exists check (see ExportsVectorsForJsReplay).
        Assert.False(Directory.Exists(missingDir));
        Assert.ThrowsAny<IOException>(() => File.WriteAllText(target, blob));
        Assert.False(Directory.Exists(missingDir));
    }
}

/// <summary>Serialized shape of the vectors file (field names match Go, all lowercase).</summary>
internal sealed class HlcVectorFileOut
{
    [System.Text.Json.Serialization.JsonPropertyName("note")]
    public string Note { get; set; } = string.Empty;

    [System.Text.Json.Serialization.JsonPropertyName("layout")]
    public string Layout { get; set; } = string.Empty;

    [System.Text.Json.Serialization.JsonPropertyName("vectors")]
    public List<HlcVector> Vectors { get; set; } = [];
}
